# we are extending everything from tomcat:8.0 image ...
FROM tomcat:9
MAINTAINER your_name
#COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY target/Lecture-4.war /usr/local/tomcat/webapps/